using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using EntityLayer;
using BusinessLayer;
using WpfLayer.Models;
using System.Windows.Input;
using System.Windows;
using PresentationLayer;
using WpfLayer.Views;

namespace WpfLayer.ViewModels
{
    public class MainViewModel: ObservableObject
    {
        //Controller class to return user object based on login credentials in the view
        private LoginController loginController = new LoginController();

        // Properties that are binded in XAML
        private string _userName;
        private string _password;
        private string _funFact;

        // Commands 
        public ICommand SignInCommand { get; private set; }
        public ICommand ShutDownCommand { get; private set; }
        public ICommand AutoGenDocCredCmd { get; private set; }
        public ICommand AutoGenRecCredCmd { get; private set; }

        public ICommand FunFactCmd { get; private set; }

        public MainViewModel()
        {
            //Initialize commands
            SignInCommand = new RelayCommand(SignIn, CanSignIn);
            ShutDownCommand = new RelayCommand(ShutDowApplication);
            AutoGenDocCredCmd = new RelayCommand(AutoGenerateDoctorCredentials);
            AutoGenRecCredCmd = new RelayCommand(AutoGenerateReceptionistCredentials);
            FunFactCmd = new RelayCommand(GenerateFunFact);

            
        }


        // Properties that are binded in XAML
        public string UserName
        {
            get { return _userName; }
            set
            {
                _userName = value;
                OnPropertyChanged();
            }
        }
        public string Password
        {
            get { return _password; }
            set
            {
                _password = value;
                OnPropertyChanged();
            }
        }

        public string FunFact
        {
            get { return _funFact; }
            set
            {
                _funFact = value;
                OnPropertyChanged();
            }
        }

        // Methos that are binded to the commands

        private bool CanSignIn()
        {
            // Implementera logik för att avgöra om inloggning är möjlig
            return !string.IsNullOrEmpty(UserName) && !string.IsNullOrEmpty(Password);
        }

        private void SignIn()
        {
            // Implementera logik för inloggning
            IUser user = loginController.CheckUserLogin(UserName, Password) as IUser;

            if (user != null)
            {
                if (user is Receptionist)
                {
                    Receptionist receptionst = (Receptionist)user;
                    ReceptionistView receptionistView = new ReceptionistView(receptionst);
                    receptionistView.Show();
                }
                else if (user is Doctor)
                {
                    Doctor doctor = (Doctor)user;
                    DoctorView doctorView = new DoctorView(doctor);
                    doctorView.ShowDialog();
                }
            }
            else
            {
                MessageBox.Show("Fel användare eller lösenord");
            }
        }

        //Other Methods for navigation
        private void ShutDowApplication()
        {
            MessageBoxResult result = MessageBox.Show("Are you sure you want to exit the application?", "Shutdown", MessageBoxButton.YesNo, MessageBoxImage.Question);
            if (result == MessageBoxResult.Yes)
            {
                Environment.Exit(0);
            }
        }

        private void AutoGenerateDoctorCredentials()
        {
            UserName = "Tom Crane";
            Password = "wowdoctorimgood123";


        }

        private void AutoGenerateReceptionistCredentials()
        {
            UserName = "Rebecca Smith";
            Password = "receptionistpass123";

        }



        private async void GenerateFunFact()
        {
            MessageBox.Show("test");

            // Använd await för att vänta på att uppgiften ska slutföras
            _funFact = await LoginController.GetTodaysFact();

            MessageBox.Show(FunFact);
        }




    }
}
